cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "nvm"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
cask "google-chrome"
cask "firefox"
cask "visual-studio-code"
cask "notion"
cask "figma"
cask "iterm2"
cask "1password"
cask "karabiner-elements"
mas "Magnet", id: 441258766
mas "DaisyDisk", id: 411643860
