cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

cask "1password"
brew "bat"
brew "bluetoothconnector"
brew "eza"
cask "figma"
cask "firefox"
brew "font-monaspace"
brew "fzf"
brew "glow"
cask "google-chrome"
brew "gum"
cask "hiddenbar"
cask "ghostty"
brew "joshmedeski/sesh/sesh"
cask "karabiner-elements"
brew "MonitorControl"
cask "notion"
brew "nvm"
brew "powerlevel10k"
brew "switchaudio-osx"
brew "sqlite"
brew "tmux"
cask "visual-studio-code"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
