#!/usr/bin/env bash

echo 'installing oh-my-zsh'
curl https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -fsSL | sh

echo 'copying .zshrc and .Brewfile'
cp ~/.dotfiles/.zshrc ~/.zshrc
cp ~/.dotfiles/.Brewfile ~/.Brewfile
